# import data

In [19]:
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter      # ganti sesuai provider                     # atau langchain_qdrant, langchain_community.vectorstores.FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

In [20]:
import pandas as pd
data = pd.read_json('/Users/muhammadzuamaalamin/Documents/RisetTextMining/retrieval2/datacorpus.json')
data

,id,pasal,bab,judul,context,ayat,buku,bagian,paragraf
0,kuhp_pasal_1,1,BAB I - RUANG LINGKUP BERLAKUNYA KETENTUAN PER...,,Pasal 1\n(1) Tidak ada satu perbuatan pun yang...,"[{'nomor': '1', 'isi': '(1) Tidak ada satu per...",NaN,NaN,NaN
1,kuhp_pasal_2,2,BAB I - RUANG LINGKUP BERLAKUNYA KETENTUAN PER...,,Pasal 2\n(1) Ketentuan sebagaimana dimaksud da...,"[{'nomor': '1', 'isi': '(1) Ketentuan sebagaim...",NaN,NaN,NaN
2,kuhp_pasal_3,3,BAB I - RUANG LINGKUP BERLAKUNYA KETENTUAN PER...,,Pasal 3\n(1) Dalam hal terdapat perubahan pera...,"[{'nomor': '1', 'isi': '(1) Dalam hal terdapat...",NaN,NaN,NaN
3,kuhp_pasal_4,4,BAB I - RUANG LINGKUP BERLAKUNYA KETENTUAN PER...,,Pasal 4\nKetentuan pidana dalam Undang-Undang ...,[],NaN,NaN,NaN
4,kuhp_pasal_5,5,BAB I - RUANG LINGKUP BERLAKUNYA KETENTUAN PER...,,Pasal 5\nKetentuan pidana dalam Undang-Undang ...,[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
616,kuhp_pasal_617,617,BAB XXXVI - KETENTUAN PERALIHAN,,Pasal 617\nPada saat Undang-Undang ini mulai b...,[],BUKU KEDUA - TINDAK PIDANA,,NaN
617,kuhp_pasal_618,618,BAB XXXVI - KETENTUAN PERALIHAN,,Pasal 618\nPada saat Undang-Undang ini mulai b...,[],BUKU KEDUA - TINDAK PIDANA,,NaN
618,kuhp_pasal_619,619,BAB XXXVI - KETENTUAN PERALIHAN,,Pasal 619\nPada saat Undang-Undang ini mulai b...,[],BUKU KEDUA - TINDAK PIDANA,,NaN
619,kuhp_pasal_620,620,BAB XXXVI - KETENTUAN PERALIHAN,,Pasal 620\nPada saat Undang-Undang ini mulai b...,[],BUKU KEDUA - TINDAK PIDANA,,NaN
620,kuhp_pasal_621,611,BAB XXXVII KETENTUAN PENUTUP,,Pasal 621\nPeraturan pelaksanaan dari Undang-U...,[],,,NaN

In [21]:
data = data.drop(columns=['id','pasal','bab','judul','ayat','buku','bagian','paragraf'])
data

                                               context
0    Pasal 1\n(1) Tidak ada satu perbuatan pun yang...
1    Pasal 2\n(1) Ketentuan sebagaimana dimaksud da...
2    Pasal 3\n(1) Dalam hal terdapat perubahan pera...
3    Pasal 4\nKetentuan pidana dalam Undang-Undang ...
4    Pasal 5\nKetentuan pidana dalam Undang-Undang ...
..                                                 ...
616  Pasal 617\nPada saat Undang-Undang ini mulai b...
617  Pasal 618\nPada saat Undang-Undang ini mulai b...
618  Pasal 619\nPada saat Undang-Undang ini mulai b...
619  Pasal 620\nPada saat Undang-Undang ini mulai b...
620  Pasal 621\nPeraturan pelaksanaan dari Undang-U...

[621 rows x 1 columns]

In [22]:
data['context'] = (data['context']
        .str.replace("\n", " ")
        .str.replace(r" +", " ", regex=True)
        .str.strip())
data

                                               context
0    Pasal 1 (1) Tidak ada satu perbuatan pun yang ...
1    Pasal 2 (1) Ketentuan sebagaimana dimaksud dal...
2    Pasal 3 (1) Dalam hal terdapat perubahan perat...
3    Pasal 4 Ketentuan pidana dalam Undang-Undang b...
4    Pasal 5 Ketentuan pidana dalam Undang-Undang b...
..                                                 ...
616  Pasal 617 Pada saat Undang-Undang ini mulai be...
617  Pasal 618 Pada saat Undang-Undang ini mulai be...
618  Pasal 619 Pada saat Undang-Undang ini mulai be...
619  Pasal 620 Pada saat Undang-Undang ini mulai be...
620  Pasal 621 Peraturan pelaksanaan dari Undang-Un...

[621 rows x 1 columns]

In [24]:
# Chunking — hasilkan list of Document, bukan plain string
splitter = RecursiveCharacterTextSplitter(
    chunk_size=4000,
    chunk_overlap=50
)

documents = []

for pasal in data['context']:
    if len(pasal) > 4000:
        # split_text → list[str], bungkus jadi Document
        splits = splitter.split_text(pasal)
        documents.extend([Document(page_content=s) for s in splits])
    else:
        documents.append(Document(page_content=pasal))

In [25]:
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
import os
# Load embeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    model_kwargs={"device": "cpu"}
)

db_path = "faiss_indexallminiLm"

# %%
# Buat atau load FAISS index
if not os.path.exists(db_path):
    vectorstore = FAISS.from_documents(documents, embeddings)  # ✅ Document objects
    vectorstore.save_local(db_path)
else:
    vectorstore = FAISS.load_local(
        db_path,
        embeddings,
        allow_dangerous_deserialization=True
    )

In [26]:
for i in range(len(documents)):
    print(documents[i].page_content)

Pasal 1 (1) Tidak ada satu perbuatan pun yang dapat dikenai sanksi pidana dan/atau tindakan, kecuali atas kekuatan peraturan pidana dalam peraturan perundang-undangan yang telah ada sebelum perbuatan dilakukan. (2) Dalam menetapkan adanya Tindak Pidana dilarang digunakan analogi.
Pasal 2 (1) Ketentuan sebagaimana dimaksud dalam Pasal 1 ayat (1) tidak mengurangi berlakunya hukum yang hidup dalam masyarakat yang menentukan bahwa seseorang patut dipidana walaupun perbuatan tersebut tidak diatur dalam Undang-Undang ini. (2) Hukum yang hidup dalam masyarakat sebagaimana dimaksud pada ayat (1) berlaku dalam tempat hukum itu hidup dan sepanjang tidak diatur dalam Undang- Undang ini dan sesuai dengan nilai-nilai yang terkandung dalam Pancasila, Undang-Undang Dasar Negara Republik Indonesia Tahun 1945, hak asasi manusia, dan asas hukum umum yang diakui masyarakat bangsa-bangsa. (3) Ketentuan mengenai tata cara dan kriteria penetapan hukum yang hidup dalam masyarakat diatur dengan Peraturan Pemerintah.
Pasal 3 (1) Dalam hal terdapat perubahan peraturan perundang- undangan sesudah perbuatan terjadi, diberlakukan peraturan perundang-undangan yang baru, kecuali ketentuan peraturan perundang-undangan yang lama menguntungkan bagi pelaku dan pembantu Tindak Pidana. (2) Dalam hal perbuatan yang terjadi tidak lagi merupakan Tindak Pidana menurut peraturan perundang- undangan yang baru, proses hukum terhadap tersangka atau terdakwa harus dihentikan demi hukum. (3) Dalam hal ketentuan sebagaimana dimaksud pada ayat (2) diterapkan bagi tersangka atau terdakwa yang berada dalam tahanan, tersangka atau terdakwa dibebaskan oleh Pejabat yang berwenang sesuai dengan tingkat pemeriksaan. (4) Dalam hal setelah putusan pemidanaan berkekuatan hukum tetap dan perbuatan yang terjadi tidak lagi merupakan Tindak Pidana menurut peraturan perundang-undangan yang baru, pelaksanaan putusan pemidanaan dihapuskan. (5) Dalam hal putusan pemidanaan telah berkekuatan hukum tetap sebagaimana dimaksud pada ayat (4), instansi atau Pejabat yang melaksanakan pembebasan merupakan instansi atau Pejabat yang berwenang. (6) Pembebasan sebagaimana dimaksud pada ayat (3) dan ayat (5) tidak menimbulkan hak bagi tersangka, terdakwa, atau terpidana menuntut ganti rugi. (7) Dalam hal setelah putusan pemidanaan berkekuatan hukum tetap dan perbuatan yang terjadi diancam dengan pidana yang lebih ringan menurut peraturan perundang-undangan yang baru, pelaksanaan putusan pemidanaan disesuaikan dengan batas pidana menurut peraturan perundang-undangan yang baru.
Pasal 4 Ketentuan pidana dalam Undang-Undang berlaku bagi Setiap Orang yang melakukan: a. Tindak Pidana di wilayah Negara Kesatuan Republik Indonesia; b. Tindak Pidana di Kapal Indonesia atau di Pesawat Udara Indonesia; atau c. Tindak Pidana di bidang teknologi informasi atau Tindak Pidana lainnya yang akibatnya dialami atau terjadi di wilayah Negara Kesatuan Republik Indonesia atau di Kapal Indonesia dan di Pesawat Udara Indonesia.
Pasal 5 Ketentuan pidana dalam Undang-Undang berlaku bagi Setiap Orang di luar wilayah Negara Kesatuan Republik Indonesia yang melakukan Tindak Pidana terhadap kepentingan Negara Kesatuan Republik Indonesia yang berhubungan dengan: a. keamanan negara atau proses kehidupan ketatanegaraan; b. martabat Presiden, Wakil Presiden, dan/ atau Pejabat Indonesia di luar negeri; c. mata uang, segel, cap negara, meterai, atau Surat berharga yang dikeluarkan oleh Pemerintah Indonesia, atau kartu kredit yang dikeluarkan oleh perbankan Indonesia; d. perekonomian, perdagangan, dan perbankan Indonesia; e. keselamatan atau keamanan pelayaran dan penerbangan; f. keselamatan atau keamanan bangunan, peralatan, dan aset nasional atau negara Indonesia; g. keselamatan atau keamanan sistem komunikasi elektronik; h. kepentingan nasional Indonesia sebagaimana ditetapkan dalam Undang-Undang; atau i. warga negara Indonesia berdasarkan perjanjian internasional dengan negara tempat terjadinya Tindak Pidana.
Pasal 6 Ketentuan pidana dalam Undang-Undang berlaku bagi Setiap Orang yang berada di luar wilayah Negara Kesatuan Republik Indonesia yang melakukan Tindak Pidana menurut hukum internasional yang telah ditetapkan sebagai Tindak Pidana dalam Undang-Undang.
Pasal 7 Ketentuan pidana dalam Undang-Undang berlaku bagi Setiap Orang yang melakukan Tindak Pidana di luar wilayah Negara Kesatuan Republik Indonesia yang penuntutannya diambil alih oleh Pemerintah Indonesia atas dasar suatu perjanjian internasional yang memberikan kewenangan kepada Pemerintah Indonesia untuk melakukan penuntutan pidana.
Pasal 8 (1) Ketentuan pidana dalam Undang-Undang berlaku bagi setiap warga negara Indonesia yang melakukan Tindak Pidana di luar wilayah Negara Kesatuan Republik Indonesia. (2) Ketentuan sebagaimana dimaksud pada ayat (1) berlaku jika perbuatan tersebut juga merupakan Tindak Pidana di negara tempat Tindak Pidana dilakukan. (3) Ketentuan sebagaimana dimaksud pada ayat (1) tidak berlaku untuk Tindak Pidana yang diancam dengan pidana denda paling banyak kategori III. (4) Penuntutan terhadap Tindak Pidana sebagaimana dimaksud pada ayat (1) dilakukan walaupun tersangka menjadi warga negara Indonesia, setelah Tindak Pidana tersebut dilakukan sepanjang perbuatan tersebut merupakan Tindak Pidana di negara tempat Tindak Pidana dilakukan. (5) Warga negara Indonesia di luar wilayah Negara Kesatuan Republik Indonesia yang melakukan Tindak Pidana sebagaimana dimaksud pada ayat (1) tidak dapat dijatuhi pidana mati jika Tindak Pidana tersebut menurut hukum negara tempat Tindak Pidana tersebut dilakukan tidak diancam dengan pidana mati.
Pasal 9 Penerapan ketentuan sebagaimana dimaksud dalam Pasal 4 sampai dengan Pasal 8 dibatasi oleh hal yang dikecualikan menurut perjanjian internasional yang berlaku.
Pasal 10 Waktu Tindak Pidana merupakan saat dilakukannya perbuatan yang dapat dipidana.
Pasal 11 Tempat Tindak Pidana merupakan tempat dilakukannya perbuatan yang dapat dipidana
Pasal 12 (1) Tindak Pidana merupakan perbuatan yang oleh peraturan perundang-undangan diancam dengan sanksi pidana dan/ atau tindakan. (2) Untuk dinyatakan sebagai Tindak Pidana, suatu perbuatan yang diancam dengan sanksi pidana dan/atau tindakan oleh peraturan perundang- undangan harus bersifat melawan hukum atau bertentangan dengan hukum yang hidup dalam masyarakat. (3) Setiap Tindak Pidana selalu bersifat melawan hukum, kecuali ada alasan pembenar.
Pasal 13 (1) Permufakatan jahat terjadi jika 2 (dua) orang atau lebih bersepakat untuk melakukan Tindak Pidana. (2) Permufakatan jahat melakukan Tindak Pidana dipidana jika ditentukan secara tegas dalam Undang-Undang. (3) Pidana untuk permufakatan jahat melakukan Tindak Pidana paling banyak I /3 (satu per tiga) dari maksimum ancaman pidana pokok untuk Tindak Pidana yang bersangkutan. (4) Permufakatan jahat melakukan Tindak Pidana yang diancam dengan pidana mati atau pidana penjara seumur hidup dipidana dengan pidana penjara paling lama 7 (tujuh) tahun. (5) Pidana tambahan untuk permufakatan jahat melakukan Tindak Pidana sama dengan pidana tambahan untuk Tindak Pidana yang bersangkutan.
Pasal 14 Permufakatan jahat melakukan Tindak Pidana tidak dipidana, jika pelaku: a. menarik diri dari kesepakatan itu; atau b. melakukan tindakan yang patut untuk mencegah terjadinya Tindak Pidana.
Pasal 15 (1) Persiapan melakukan Tindak Pidana terjadi jika pelaku berusaha untuk mendapatkan atau menyiapkan sarana berupa alat, mengumpulkan informasi atau menyusun perencanaan tindakan, atau melakukan tindakan serupa yang dimaksudkan untuk menciptakan kondisi untuk dilakukannya suatu perbuatan yang secara langsung ditujukan bagi penyelesaian Tindak Pidana. (2) Persiapan melakukan Tindak Pidana dipidana, jika ditentukan secara tegas dalam Undang-Undang. (3) Pidana untuk persiapan melakukan Tindak Pidana paling banyak l/2 (satu per dua) dari maksimum ancaman pidana pokok untuk Tindak Pidana yang bersangkutan. (4) Persiapan melakukan Tindak Pidana yang diancam dengan pidana mati atau pidana penjara seumur hidup dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun. (5) Pidana tambahan untuk persiapan melakukan Tindak Pidana sama dengan pidana tambahan untuk Tindak Pidana yang bersangkutan.
Pasal 16 Persiapan melakukan Tindak Pidana tidak dipidana jika pelaku menghentikan atau mencegah kemungkinan terciptanya kondisi sebagaimana dimaksud dalam Pasal 15 ayat (1).
Pasal 17 (1) Percobaan melakukan Tindak Pidana terjadi jika niat pelaku telah nyata dari adanya permulaan pelaksanaan dari Tindak Pidana yang ditqju, tetapi pelaksanaannya tidak selesai, tidak mencapai hasil, atau tidak menimbulkan akibat yang dilarang, bukan karena semata-mata atas kehendaknya sendiri. (2) Permulaan pelaksanaan sebagaimana dimaksud pada ayat (1) terjadi jika: a. perbuatan yang dilakukan itu diniatkan atau ditqiukan untuk te{adinya Tindak Pidana; dan b. perbuatan yang dilakukan langsung berpotensi menimbulkan Tindak Pidana yang dituju. (3) Pidana untuk percobaan melakukan Tindak Pidana paling banyak 2/3 (dua per tiga) dari maksimum ancaman pidana pokok untuk Tindak Pidana yang bersangkutan. (4) Percobaan melakukan Tindak Pidana yang diancam dengan pidana mati atau pidana penjara seumur hidup, dipidana dengan pidana penjara paling lama 15 (lima belas) tahun. (5) Pidana tambahan untuk percobaan melakukan Tindak Pidana sama dengan pidana tambahan untuk Tindak Pidana yang bersangkutan.
Pasal 18 (1) Percobaan melakukan Tindak Pidana tidak dipidana jika pelaku setelah melakukan permulaan pelaksanaan sebagaimana dimaksud dalam Pasal 17 ayat (1): a. tidak menyelesaikan perbuatannya karena kehendaknya sendiri secara sukarela; atau b. dengan kehendaknya sendiri mencegah tercapainya tujuan atau akibat perbuatannya. (2) Dalam hal percobaan sebagaimana dimaksud pada ayat (1) telah menimbulkan kerugian atau menurut peraturan perundang-undangan mempakan Tindak Pidana tersendiri, pelaku dapat dipertanggungiawabkan untuk Tindak Pidana tersebut.
Pasal 19 Percobaan melakukan Tindak Pidana yang hanya diancam dengan pidana denda paling banyak kategori II, tidak dipidana.
Pasal 20 Setiap Orang dipidana sebagai pelaku Tindak Pidana jika: a. melakukan sendiri Tindak Pidana; b. melakukan Tindak Pidana dengan perantaraan alat atau menyuruh orang lain yang tidak dapat dipertan ggun gj awabkan ; c. turut serta melakukan Tindak Pidana; atau d. menggerakkan orang lain supaya melakukan Tindak Pidana dengan cara memberi atau menjanjikan sesuatu, menyalahgunakan kekuasaan atau martabat, melakukan Kekerasan, menggunakan Ancaman Kekerasan, melakukan penyesatan, atau dengan memberi kesempatan, sarana, atau keterangan.
Pasal 21 (1) Setiap Orang dipidana sebagai pembantu Tindak Pidana jika dengan sengaja: a. memberi kesempatan, sarana, atau keterangan untuk melakukan Tindak Pidana; atau b. memberi bantuan pada waktu Tindak Pidana dilakukan. (2) Ketentuan sebagaimana dimaksud pada ayat (1) tidak berlaku untuk pembantuan melakukan Tindak Pidana yang hanya diancam dengan pidana denda paling banyak kategori II. (3) Pidana untuk pembantuan melakukan Tindak Pidana paling banyak 213 (dua per tiga) dari maksimum ancaman pidana pokok untuk Tindak Pidana yang bersangkutan. (4) Pembantuan melakukan Tindak Pidana yang diancam dengan pidana mati atau pidana penjara seumur hidup, dipidana dengan pidana penjara paling lama 15 (lima belas) tahun. (5) Pidana tambahan untuk pembantuan melakukan Tindak Pidana sama dengan pidana tambahan untuk Tindak Pidana yang bersangkutan.
Pasal 22 Keadaan pribadi pelaku sebagaimana dimaksud dalam Pasal 2O atau pembantu sebagaimana dimaksud dalam Pasal 21 dapat menghapus, mengurangi, atau memperberat pidananya.
Pasal 23 (1) Pengulangan Tindak Pidana terjadi jika Setiap Orang: a. melakukan Tindak Pidana kembali dalam waktu 5 (lima) tahun setelah menjalani seluruh atau sebagian pidana pokok yang dijatuhkan atau pidana pokok yang dijatuhkan telah dihapuskan; atau b. pada waktu melakukan Tindak Pidana, kewajiban menjalani pidana pokok yang dijatuhkan terdahulu belum kedaluwarsa. (2) Tindak Pidana sebagaimana dimaksud pada ayat (1) mencangkup Tindak Pidana yang diancam dengan pidana minimum khusus, pidana penjara 4 (empat) tahun atau lebih, atau pidana denda paling sedikit kategori III. (3) Ketentuan sebagaimana dimaksud pada ayat (1) juga berlaku untuk Tindak Pidana mengenai penganiayaan.
Pasal 24 (1) Dalam hal tertentu, pelaku Tindak Pidana hanya dapat dituntut atas dasar pengaduan. (2) Tindak Pidana aduan harus ditentukan secara tegas dalam Undang-Undang.
Pasal 25 (1) Dalam hal Korban Tindak Pidana aduan belum berumur 16 (enam belas) tahun, yang berhak mengadu merupakan Orang Tua atau walinya. (2) Dalam hal Orang Tua atau wali sebagaimana dimaksud pada ayat (1) tidak ada atau Orang Tua atau wali itu sendiri yang harus diadukan, pengaduan dilakukan oleh keluarga sedarah dalam garis lurus. (3) Dalam hal keluarga sedarah dalam garis lurus sebagaimana dimaksud pada ayat (2) tidak ada, pengaduan dilakukan oleh keluarga sedarah dalam garis menyamping sampai derajat ketiga. (4) Dalam hal Korban Tindak Pidana sebagaimana dimaksud pada ayat (1) tidak memiliki Orang Tua, wali, atau keluarga sedarah dalam garis lurus ke atas ataupun menyamping sampai derajat ketiga, pengaduan dilakukan oleh diri sendiri dan/atau pendamping.
Pasal 26 (1) Dalam hal Korban Tindak Pidana aduan berada di bawah pengampuan, yang berhak mengadu merupakan pengampunya, kecuali bagi Korban Tindak Pidana aduan yang berada dalam pengampuan karena boros. (2) Dalam hal pengampu sebagaimana dimaksud pada ayat (1) tidak ada atau pengampu itu sendiri yang harus diadukan, pengaduan dilakukan oleh suami atau istri Korban atau keluarga sedarah dalam garis lurus. (3) Dalam hal suami atau istri Korban atau keluarga sedarah dalam garis lurus sebagaimana dimaksud pada ayat (2) tidak ada, pengaduan dilakukan oleh keluarga sedarah dalam garis menyamping sampai derajat ketiga.
Pasal 27 Dalam hal Korban Tindak Pidana aduan meninggal dunia, pengaduan dapat dilakukan oleh Orang Tua, anak, suami, atau istri Korban, kecuali jika Korban sebelumnya secara tegas tidak menghendaki adanya penuntutan.
Pasal 28 (1) Pengaduan dilakukan dengan cara menyampaikan pemberitahuan dan permohonan untuk dituntut. (2) Pengaduan sebagaimana dimaksud pada ayat (1) diajukan secara lisan atau tertulis kepada Pejabat yang berwenang.
Pasal 29 (1) Pengaduan harus diajukan dalam tenggang waktu: a. 6 (enam) Bulan terhitung sejak tanggal orang yang berhak mengadu mengetahui adanya Tindak Pidana jika yang berhak mengadu bertempat tinggal di wilayah Negara Kesatuan Republik Indonesia; atau b. 9 (sembilan) Bulan terhitung sejak tanggal orang yang berhak mengadu mengetahui adanya Tindak Pidana jika yang berhak mengadu bertempat tinggal di luar wilayah Negara Kesatuan Republik Indonesia. (2) Jika yang berhak mengadu lebih dari 1 (satu) orang, tenggang waktu sebagaimana dimaksud pada ayat (1) dihitung sejak tanggal masing-masing pengadu mengetahui adanya Tindak Pidana.
Pasal 30 (1) Pengaduan dapat ditarik kembali oleh pengadu dalam waktu 3 (tiga) Bulan terhitung sejak tanggal pengaduan diajukan. (2) Pengaduan yang ditarik kembali tidak dapat diajukan lagi.
Pasal 31 Setiap Orang yang melakukan perbuatan yang dilarang tidak dipidana, jika perbuatan tersebut dilakukan untuk melaksanakan ketentuan peraturan perundang-undangan.
Pasal 32 Setiap Orang yang melakukan perbuatan yang dilarang tidak dipidana, jika perbuatan tersebut dilakukan untuk melaksanakan perintah jabatan dari Pejabat yang berwenang.
Pasal 33 Setiap Orang yang melakukan perbuatan yang dilarang tidak dipidana, jika perbuatan tersebut dilakukan karena keadaan darurat.
Pasal 34 Setiap Orang yang terpaksa melakukan perbuatan yang dilarang tidak dipidana, jika perbuatan tersebut dilakukan karena pembelaan terhadap serangan atau ancaman serangan seketika yang melawan hukum terhadap diri sendiri atau orang lain, kehormatan dalam arti kesusilaan, atau harta benda sendiri atau orang lain.
Pasal 35 Ketiadaan sifat melawan hukum dari Tindak Pidana sebagaimana dimaksud dalam Pasal 12 ayat (2) merupakan alasan pembenar.
Pasal 36 (1) Setiap Orang hanya dapat dimintai pertanggungjawaban atas Tindak Pidana yang dilakukan dengan sengaja atau karena kealpaan. (2) Perbuatan yang dapat dipidana merupakan Tindak Pidana yang dilakukan dengan sengaja, sedangkan Tindak Pidana yang dilakukan karena kealpaan dapat dipidana jika secara tegas ditentukan dalam peraturan perundang-undangan.
Pasal 37 Dalam hal ditentukan oleh Undang-Undang, Setiap Orang dapat: a. dipidana semata-mata karena telah dipenuhinya unsur- unsur Tindak Pidana tanpa memperhatikan adanya kesalahan; atau b. dimintai pertanggungiawaban atas Tindak Pidana yang dilakukan oleh orang lain.
Pasal 38 Setiap Orang yang pada waktu melakukan Tindak Pidana menyandang disabilitas mental dan/atau disabilitas intelektual dapat dikurangi pidananya dan/atau dikenai tindakan.
Pasal 39 Setiap Orang yang pada waktu melakukan Tindak Pidana menyandang disabilitas mental yang dalam keadaan kekambuhan akut dan disertai gambaran psikotik dan/ atau disabilitas intelektual derajat sedang atau berat tidak dapat dijatuhi pidana, tetapi dapat dikenai tindakan.
Pasal 40 Pertanggungjawaban pidana tidak dapat dikenakan terhadap anak yang pada waktu melakukan Tindak Pidana belum berumur 12 (dua belas) tahun.
Pasal 41 Dalam hal anak yang belum berumur 12 (dua belas) tahun melakukan atau diduga melakukan Tindak Pidana, penyidik, pembimbing kemasyarakatan, dan pekerja sosial profesional mengambil keputusan untuk: a. menyerahkan kembali kepada Orang Tua/wali; atau b. mengikutsertakan dalam program pendidikan, pembinaan, dan pembimbingan di instansi pemerintah atau lembaga penyelenggaraan kesejahteraan sosial di instansi yang menangani bidang kesejahteraan sosial, baik pada tingkat pusat maupun daerah, paling lama 6 (enam) Bulan.
Pasal 42 Setiap Orang yang melakukan Tindak Pidana tidak dipidana karena: a. dipaksa oleh kekuatan yang tidak dapat ditahan; atau b. dipaksa oleh adanya ancaman, tekanan, atau kekuatan yang tidak dapat dihindari.
Pasal 43 Setiap Orang yang melakukan pembelaan terpaksa yang melampaui batas yang langsung disebabkan keguncangan jiwa yang hebat karena serangan atau ancaman serangan seketika yang melawan hukum, tidak dipidana.
Pasal 44 Perintah jabatan yang diberikan tanpa wewenang tidak mengakibatkan hapusnya pidana, kecuali jika orang yang diperintahkan dengan iktikad baik mengira bahwa perintah tersebut diberikan dengan wewenang dan pelaksanaannya, termasuk dalam lingkup pekerjaannya.
Pasal 45 (1) Korporasi merupakan subjek Tindak Pidana. (2) Korporasi sebagaimana dimaksud pada ayat (1) mencakup badan hukum yang berbentuk perseroan terbatas, yayasan, koperasi, badan usaha milik negara, badan usaha milik daerah, atau yang disamakan dengan itu, serta perkumpulan baik yang berbadan hukum maupun tidak berbadan hukum, badan usaha yang berbentuk firma, persekutuan komanditer, atau yang disamakan dengan itu sesuai dengan ketentuan peraturan perundang-undangan.
Pasal 46 Tindak Pidana oleh Korporasi merupakan Tindak Pidana yang dilakukan oleh pengurus yang mempunyai kedudukan fungsional dalam struktur organisasi Korporasi atau orang yang berdasarkan hubungan kerja atau berdasarkan hubungan lain yang bertindak untuk dan atas nama Korporasi atau bertindak demi kepentingan Korporasi, dalam lingkup usaha atau kegiatan Korporasi tersebut, baik secara sendiri-sendiri maupun bersama-sama.
Pasal 47 Selain ketentuan sebagaimana dimaksud dalam Pasal 46, Tindak Pidana oleh Korporasi dapat dilakukan oleh pemberi perintah, pemegang kendali, atau pemilik manfaat Korporasi yang berada di luar struktur organisasi, tetapi dapat mengendalikan Korporasi.

In [27]:
query = "Kalau menghina Presiden di media sosial, ancamannya berapa?"

results = vectorstore.similarity_search_with_score(query, k=10)

for i, (doc, score) in enumerate(results, 1):
    print(f"\nResult {i} | score={score:.4f}")
    print(doc.page_content[:400])

Result 1 | score=18.4832
Pasal 218 (1) Setiap Orang yang Di Muka Umum menyerang kehormatan atau harkat dan martabat diri Presiden dan/atau Wakil Presiden, dipidana dengan pidana penjara paling lama 3 (tiga) tahun atau pidana denda paling banyak kategori IV. (2) Tidak merupakan penyerangan kehormatan atau harkat dan martabat sebagaimana dimaksud pada ayat (1), jika perbuatan dilakukan untuk kepentingan umum atau pembelaan

Result 2 | score=18.8488
Pasal 217 Setiap Orang yang menyerang diri Presiden dan/atau Wakil Presiden yang tidak termasuk dalam ketentuan pidana yang lebih berat, dipidana dengan pidana penjara paling lama 5 (lima) tahun.

Result 3 | score=19.3270
Pasal 219 Setiap Orang yang menyiarkan, mempertunjukkan, atau menempelkan tulisan atau gambar sehingga terlihat oleh umum, memperdengarkan rekaman sehingga terdengar oleh umum, atau menyebarluaskan dengan sarana teknologi informasi yang berisi penyerangan kehormatan atau harkat dan martabat terhadap Presiden dan/atau Wakil Presiden dengan maksud agar isinya diketahui atau lebih diketahui umum, dip

Result 4 | score=19.5525
Pasal 264 Setiap Orang yang menyiarkan berita yang tidak pasti, berlebih-lebihan, atau yang tidak lengkap sedangkan diketahuinya atau patut diduga, bahwa berita demikian dapat mengakibatkan kerusuhan di masyarakat, dipidana dengan pidana penjara paling lama 2 (dua) tahun atau pidana denda paling banyak kategori III.

Result 5 | score=19.8792
Pasal 263 (1) Setiap Orang yang menyiarkan atau menyebarluaskan berita atau pemberitahuan padahal diketahuinya bahwa berita atau pemberitahuan tersebut bohong yang mengakibatkan kerusuhan dalam masyarakat, dipidana dengan pidana penjara paling lama 6 (enam) tahun atau pidana denda paling banyak kategori V. (2) Setiap Orang yang menyiarkan atau menyebarluaskan berita atau pemberitahuan padahal patu

Result 6 | score=20.4706
Pasal 191 Setiap Orang yang melakukan Makar dengan maksud membunuh atau merampas kemerdekaan Presiden dan/atau Wakil Presiden atau menjadikan Presiden dan/atau Wakil Presiden tidak mampu menjalankan pemerintahan, dipidana dengan pidana mati, pidana penjara seumur hidup, atau pidana penjara paling lama 20 (dua puluh) tahun.

Result 7 | score=20.7142
Pasal 433 (1) Setiap Orang yang dengan lisan menyerang kehormatan atau nama baik orang lain dengan cara menuduhkan suatu hal, dengan maksud supaya hal tersebut diketahui umum, dipidana karena pencemaran, dengan pidana penjara paling lama 9 (sembilan) Bulan atau pidana denda paling banyak kategori II. (2) Jika perbuatan sebagaimana dimaksud pada ayat (1) dilakukan dengan tulisan atau gambar yang di

Result 8 | score=20.9328
Pasal 436 Penghinaan yang tidak bersifat pencemaran atau pencemaran tertulis yang dilakukan terhadap orang lain baik Di Muka Umum dengan lisan atau tulisan, maupun di muka orang yang dihina tersebut secara lisan atau dengan perbuatan atau dengan tulisan yang dikirimkan atau diterimakan kepadanya, dipidana karena penghinaan ringan dengan pidana penjara paling lama 6 (enam) Bulan atau pidana denda p

Result 9 | score=20.9842
Pasal 21 (1) Setiap Orang dipidana sebagai pembantu Tindak Pidana jika dengan sengaja: a. memberi kesempatan, sarana, atau keterangan untuk melakukan Tindak Pidana; atau b. memberi bantuan pada waktu Tindak Pidana dilakukan. (2) Ketentuan sebagaimana dimaksud pada ayat (1) tidak berlaku untuk pembantuan melakukan Tindak Pidana yang hanya diancam dengan pidana denda paling banyak kategori II. (3) P

Result 10 | score=20.9967
Pasal 240 (1) Setiap Orang yang Di Muka Umum dengan lisan atau tulisan menghina pemerintah atau lembaga negara, dipidana dengan pidana penjara paling lama 1 (satu) tahun 6 (enam) Bulan atau pidana denda paling banyak kategori II. (2) Dalam hal Tindak Pidana sebagaimana dimaksud pada ayat (1) berakibat terjadinya kerusuhan dalam masyarakat, dipidana dengan pidana penjara paling lama 3 (tiga) tahun

In [28]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever

bm25 = BM25Retriever.from_documents(documents)
bm25.k = 5

vector_retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25, vector_retriever],
    weights=[0.5, 0.5]
)

In [29]:
query = "Kalau menghina Presiden di media sosial, ancamannya berapa?"

docs = hybrid_retriever.get_relevant_documents(query)

for i, (doc, score) in enumerate(results, 1):
    print(f"\nResult {i} | score={score:.4f}")
    print(f"Halaman: {doc.metadata.get('page')}")
    print(doc.page_content[:400])

Result 1 | score=18.4832
Halaman: None
Pasal 218 (1) Setiap Orang yang Di Muka Umum menyerang kehormatan atau harkat dan martabat diri Presiden dan/atau Wakil Presiden, dipidana dengan pidana penjara paling lama 3 (tiga) tahun atau pidana denda paling banyak kategori IV. (2) Tidak merupakan penyerangan kehormatan atau harkat dan martabat sebagaimana dimaksud pada ayat (1), jika perbuatan dilakukan untuk kepentingan umum atau pembelaan

Result 2 | score=18.8488
Halaman: None
Pasal 217 Setiap Orang yang menyerang diri Presiden dan/atau Wakil Presiden yang tidak termasuk dalam ketentuan pidana yang lebih berat, dipidana dengan pidana penjara paling lama 5 (lima) tahun.

Result 3 | score=19.3270
Halaman: None
Pasal 219 Setiap Orang yang menyiarkan, mempertunjukkan, atau menempelkan tulisan atau gambar sehingga terlihat oleh umum, memperdengarkan rekaman sehingga terdengar oleh umum, atau menyebarluaskan dengan sarana teknologi informasi yang berisi penyerangan kehormatan atau harkat dan martabat terhadap Presiden dan/atau Wakil Presiden dengan maksud agar isinya diketahui atau lebih diketahui umum, dip

Result 4 | score=19.5525
Halaman: None
Pasal 264 Setiap Orang yang menyiarkan berita yang tidak pasti, berlebih-lebihan, atau yang tidak lengkap sedangkan diketahuinya atau patut diduga, bahwa berita demikian dapat mengakibatkan kerusuhan di masyarakat, dipidana dengan pidana penjara paling lama 2 (dua) tahun atau pidana denda paling banyak kategori III.

Result 5 | score=19.8792
Halaman: None
Pasal 263 (1) Setiap Orang yang menyiarkan atau menyebarluaskan berita atau pemberitahuan padahal diketahuinya bahwa berita atau pemberitahuan tersebut bohong yang mengakibatkan kerusuhan dalam masyarakat, dipidana dengan pidana penjara paling lama 6 (enam) tahun atau pidana denda paling banyak kategori V. (2) Setiap Orang yang menyiarkan atau menyebarluaskan berita atau pemberitahuan padahal patu

Result 6 | score=20.4706
Halaman: None
Pasal 191 Setiap Orang yang melakukan Makar dengan maksud membunuh atau merampas kemerdekaan Presiden dan/atau Wakil Presiden atau menjadikan Presiden dan/atau Wakil Presiden tidak mampu menjalankan pemerintahan, dipidana dengan pidana mati, pidana penjara seumur hidup, atau pidana penjara paling lama 20 (dua puluh) tahun.

Result 7 | score=20.7142
Halaman: None
Pasal 433 (1) Setiap Orang yang dengan lisan menyerang kehormatan atau nama baik orang lain dengan cara menuduhkan suatu hal, dengan maksud supaya hal tersebut diketahui umum, dipidana karena pencemaran, dengan pidana penjara paling lama 9 (sembilan) Bulan atau pidana denda paling banyak kategori II. (2) Jika perbuatan sebagaimana dimaksud pada ayat (1) dilakukan dengan tulisan atau gambar yang di

Result 8 | score=20.9328
Halaman: None
Pasal 436 Penghinaan yang tidak bersifat pencemaran atau pencemaran tertulis yang dilakukan terhadap orang lain baik Di Muka Umum dengan lisan atau tulisan, maupun di muka orang yang dihina tersebut secara lisan atau dengan perbuatan atau dengan tulisan yang dikirimkan atau diterimakan kepadanya, dipidana karena penghinaan ringan dengan pidana penjara paling lama 6 (enam) Bulan atau pidana denda p

Result 9 | score=20.9842
Halaman: None
Pasal 21 (1) Setiap Orang dipidana sebagai pembantu Tindak Pidana jika dengan sengaja: a. memberi kesempatan, sarana, atau keterangan untuk melakukan Tindak Pidana; atau b. memberi bantuan pada waktu Tindak Pidana dilakukan. (2) Ketentuan sebagaimana dimaksud pada ayat (1) tidak berlaku untuk pembantuan melakukan Tindak Pidana yang hanya diancam dengan pidana denda paling banyak kategori II. (3) P

Result 10 | score=20.9967
Halaman: None
Pasal 240 (1) Setiap Orang yang Di Muka Umum dengan lisan atau tulisan menghina pemerintah atau lembaga negara, dipidana dengan pidana penjara paling lama 1 (satu) tahun 6 (enam) Bulan atau pidana denda paling banyak kategori II. (2) Dalam hal Tindak Pidana sebagaimana dimaksud pada ayat (1) berakibat terjadinya kerusuhan dalam masyarakat, dipidana dengan pidana penjara paling lama 3 (tiga) tahun

# model

In [30]:
from langchain.prompts import ChatPromptTemplate

# ── Versi Ringan untuk Model 4B ───────────────────────────────────────────
prompt_template = ChatPromptTemplate.from_template("""
Kamu adalah ahli hukum KUHP Indonesia.
Jawab berdasarkan konteks berikut saja.

Konteks:
{context}

Pertanyaan:
{question}

Jawaban (sebutkan nomor pasal dan ancaman hukumannya):
""")

# model 1b

In [31]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Berapa denda maksimal kalau ketahuan main judi online??"}
)

print(response["result"])

Berdasarkan konteks yang diberikan, denda maksimal jika ketahuan main judi online adalah **Rp50.000.000,00 (lima puluh juta rupiah)**. Ini tercantum dalam Pasal 427 ayat (2) yang menyatakan "pidana denda paling banyak kategori III".

In [32]:
from langchain.prompts import ChatPromptTemplate

prompt_template = ChatPromptTemplate.from_template("""
Kamu adalah ahli hukum KUHP Indonesia.
Jawab HANYA berdasarkan konteks dokumen di bawah ini.

Konteks:
{context}

Pertanyaan:
{question}

Instruksi jawaban:
- Sebutkan semua pasal yang relevan, bisa lebih dari satu.
- Format tiap pasal seperti contoh di bawah.
- Urutkan dari pasal paling utama.
- Jika tidak ditemukan, jawab: "Pasal tidak ditemukan dalam dokumen."

Contoh format jawaban:
Pasal 433: Pencemaran lisan di muka umum → Ancaman: penjara 9 bulan
Pasal 441: Pencemaran melalui tulisan/media → Ancaman: penjara 1 tahun 6 bulan

Jawaban:
""")

In [33]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Berapa denda maksimal kalau ketahuan main judi online??"}
)

print(response["result"])

Pasal 427: Setiap Orang yang menggunakan kesempatan main judi yang diadakan tanpa izin → Ancaman: pidana penjara paling lama 3 (tiga) tahun atau pidana denda paling banyak kategori III.

Pasal 426 (1): Setiap Orang yang tanpa izin menawarkan atau memberi kesempatan untuk main judi dan menjadikan sebagai mata pencaharian atau turut serta dalam perusahaan perjudian; menawarkan atau memberi kesempatan kepada umum untuk main judi atau turut serta dalam perusahaan perjudian, terlepas dari ada tidaknya suatu syarat atau tata cara yang harus dipenuhi untuk menggunakan kesempatan tersebut; menjadikan turut serta pada permainan judi sebagai mata pencaharian → Ancaman: pidana penjara paling lama 9 (sembilan) tahun atau pidana denda paling banyak kategori VI.

Pasal 84: Setiap Orang yang telah berulang kali dijatuhi pidana denda untuk Tindak Pidana yang hanya diancam dengan pidana denda paling banyak kategori II → Ancaman: pidana pengawasan paling lama 6 (enam) Bulan dan pidana denda yang diperberat paling banyak 1/3 (satu per tiga).

In [35]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Berapa hukuman maksimal kalau memukul orang dengan terencana dan orang tersebut meninggal??"}
)

print(response["result"])

Pasal 458 (1): Setiap Orang yang merampas nyawa orang lain, dipidana karena pembunuhan, dengan pidana penjara paling lama 15 (lima belas) tahun.
Pasal 458 (2): Jika Tindak Pidana sebagaimana dimaksud pada ayat (1) dilakukan terhadap ibu, Ayah, istri, suami, atau anaknya, pidananya dapat ditambah 1/3 (satu per tiga).
Pasal 462: Setiap Orang yang mendorong, membantu, atau memberi sarana kepada orang lain untuk bunuh diri dan orang tersebut mati karena bunuh diri, dipidana dengan pidana penjara paling lama 4 (empat) tahun.
Pasal 468 (2): Jika perbuatan sebagaimana dimaksud pada ayat (1) mati, dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun.

In [36]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Joko mencuri hasil pertanian dengan terencana kira kira joko akan mendapatkan hukuman apa ???"}
    
)

print(response["result"])

Pasal 592: Setiap Orang yang menjadikan kebiasaan untuk membeli, menukar, menerima jaminan atau gadai, menyimpan, atau menyembunyikan benda yang diperoleh dari Tindak Pidana, dipidana dengan pidana penjara paling lama 6 (enam) tahun atau pidana denda paling banyak kategori V.

Pasal 15: Persiapan melakukan Tindak Pidana terjadi jika pelaku berusaha untuk mendapatkan atau menyiapkan sarana berupa alat, mengumpulkan informasi atau menyusun perencanaan tindakan, atau melakukan tindakan serupa yang dimaksudkan untuk menciptakan kondisi untuk dilakukannya suatu perbuatan yang secara langsung ditujukan bagi penyelesaian Tindak Pidana. Persiapan melakukan Tindak Pidana dipidana, jika ditentukan secara tegas dalam Undang-Undang. Pidana untuk persiapan melakukan Tindak Pidana paling banyak l/2 (satu per dua) dari maksimum ancaman pidana pokok untuk Tindak Pidana yang bersangkutan.

In [37]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "apa itu restorasi justice ???"}
    
)

print(response["result"])

Pasal tidak ditemukan dalam dokumen.

In [42]:
from langchain.prompts import ChatPromptTemplate

prompt_template = ChatPromptTemplate.from_template("""
Kamu adalah asisten hukum Indonesia yang membantu menjelaskan aturan KUHP dengan bahasa yang mudah dipahami.

Konteks (kutipan pasal KUHP):
{context}

Pertanyaan:
{question}

Instruksi:
- Jawab pertanyaan berdasarkan konteks di atas.
- Gunakan bahasa yang jelas dan mudah dipahami.
- Sertakan nomor pasal sebagai referensi di akhir jawaban.
- Jika konteks tidak relevan, jawab: "Informasi tidak ditemukan dalam dokumen."

Contoh:
Pertanyaan: Apakah menghina orang di depan umum bisa dipidana?
Jawaban: Ya, menghina orang secara lisan di depan umum dapat dikenakan pidana penjara hingga 9 bulan. Jika penghinaan dilakukan melalui tulisan atau media, ancamannya lebih berat yaitu hingga 1 tahun 6 bulan. [Ref: Pasal 433, Pasal 441]

Jawaban:
""")

In [43]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Apa hukuman untuk orang yang melakukan persetubuhan dengan orang yang bukan suami/istrinya???"}
    
)

print(response["result"])

Hukuman untuk orang yang melakukan persetubuhan dengan orang yang bukan suami/istrinya adalah sebagai berikut:

Pasal 411 (1) mengatur mengenai perzinaan. Jika seseorang melakukan persetubuhan dengan orang yang bukan suaminya atau istrinya, maka akan dipidana karena perzinaan. Pidana yang diterapkan adalah pidana penjara paling lama 1 (satu) tahun atau pidana denda paling banyak kategori II. [Ref: Pasal 411 ayat (1)]

Selain itu, terdapat juga Pasal 413 yang mengatur mengenai persetubuhan dengan anggota keluarga dekat (anak, saudara kandung, atau sepupu tingkat pertama). Dalam pasal ini, pelaku dapat dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun. [Ref: Pasal 413]

In [47]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "apa jenis hukuman yang bisa diberikan untuk anak ?"}
    
)

print(response["result"])

Berdasarkan konteks yang diberikan, jenis hukuman yang bisa diberikan untuk anak bervariasi tergantung pasal yang berlaku. Berikut rinciannya:

*   **Pasal 425 (1) dan (2):** Hukuman penjara paling lama 4 tahun atau denda paling banyak kategori IV jika memberikan anak di bawah 12 tahun kepada orang lain untuk dimanfaatkan dalam melakukan perbuatan meminta-minta atau pekerjaan berbahaya.
*   **Pasal 452 (1):** Hukuman penjara paling lama 6 tahun atau denda paling banyak kategori IV jika menarik anak dari kekuasaan sesuai peraturan. Jika dengan tipu muslihat, kekerasan, atau ancaman kekerasan, hukuman penjara paling lama 8 tahun atau denda paling banyak kategori V.
*   **Pasal 453 (1) dan (2):** Hukuman penjara paling lama 4 tahun atau denda paling banyak kategori III jika menyembunyikan atau menarik anak dari kekuasaan. Jika terhadap anak di bawah 12 tahun, hukuman penjara paling lama 7 tahun.
*   **Pasal 430:** Hukuman 1/2 dari pidana sebagaimana dimaksud dalam Pasal 429 ayat (1) dan (2) jika seorang ibu membuang atau meninggalkan anaknya setelah kelahiran.
*   **Pasal 341:** Hukuman penjara paling lama 6 bulan atau denda paling banyak kategori II jika membiarkan anak tanpa pengawasan sehingga menimbulkan bahaya.

Selain pidana pokok, terdapat juga pidana tambahan seperti yang tercantum dalam Paragraf 3 Pidana Pasal 114.

**Referensi:** Pasal 425, Pasal 429, Pasal 430, Pasal 452, Pasal 453, Pasal 341, Pasal 114.

In [44]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Berapa denda kalau mengganggu ibadah orang lain di tempat ibadah???"}
    
)

print(response["result"])

Mengganggu ibadah orang lain di tempat ibadah dapat dipidana dengan denda. Berdasarkan Pasal 303 (1) KUHP, jika seseorang membuat gaduh di dekat tempat untuk menjalankan ibadah pada waktu ibadah sedang berlangsung, maka akan dipidana dengan pidana denda paling banyak kategori I.

[Ref: Pasal 303 (1) KUHP]

In [40]:
from langchain.prompts import ChatPromptTemplate

prompt_template = ChatPromptTemplate.from_template("""
Kamu adalah asisten hukum Indonesia. Jawab pertanyaan berdasarkan konteks berikut dengan bahasa yang mudah dipahami. Jika tidak ada informasi yang relevan, jawab: "Informasi tidak tersedia."

Konteks:
{context}

Contoh:
Pertanyaan: Apakah menghina orang di depan umum bisa dipidana?
Jawaban: Ya, bisa dipidana penjara hingga 9 bulan. Jika lewat tulisan atau media, ancamannya hingga 1 tahun 6 bulan. [Pasal 433, 441]

Pertanyaan: {question}
Jawaban:
""")

In [41]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Apa hukuman untuk orang yang melakukan persetubuhan dengan orang yang bukan suami/istrinya???"}
    
)

print(response["result"])

Hukuman untuk melakukan persetubuhan dengan orang yang bukan suami/istrinya adalah:

*   **Persetubuhan di luar perkawinan:** Pidana penjara paling lama 1 (satu) tahun atau pidana denda paling banyak kategori II.
*   **Pengaduan:** Penuntutan hanya dilakukan atas pengaduan suami/istri atau orang tua (jika tidak ada perkawinan).

Informasi tidak tersedia.

## Testing

In [14]:
from langchain.chains import RetrievalQA
from langchain_ollama import ChatOllama

llm = ChatOllama(model="gemma3:4b", temperature=0.1)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=hybrid_retriever,
    chain_type="stuff",
    chain_type_kwargs={"prompt": prompt_template},
    return_source_documents=True
)
response = qa_chain.invoke(
    {"query": "Berapa denda maksimal kalau ketahuan main judi online??"}
)

print(response["result"])

Berdasarkan dokumen KUHP yang tersedia, berikut adalah analisis mengenai denda maksimal jika ketahuan main judi online:

**1. Pasal-pasal KUHP yang Relevan:**

*   **Pasal 427:** Setiap Orang yang menggunakan kesempatan main judi yang diadakan tanpa izin, dipidana dengan pidana penjara paling lama 3 (tiga) tahun atau pidana denda paling banyak kategori III.
*   **Pasal 78 (1):** Pidana denda merupakan sejumlah uang yang wajib dibayar oleh terpidana berdasarkan putusan pengadilan.
*   **Pasal 78 (2):** Jika tidak ditentukan minimum khusus, pidana denda ditetapkan paling sedikit Rp50.000,00 (lima puluh ribu rupiah).

**2. Unsur-unsur Pidana yang Terpenuhi:**

Kasus main judi online, berdasarkan Pasal 427, memerlukan unsur-unsur sebagai berikut:

*   **Keberadaan Tindak Permainan Judi:**  Main judi online secara umum memenuhi unsur ini.
*   **Penggunaan Kesempatan:** Terpidana menggunakan kesempatan yang disediakan dalam permainan judi online tersebut.
*   **Tanpa Izin:** Permainan judi online tersebut diadakan tanpa izin yang sah.

**3. Ancaman Hukuman Sesuai Pasal yang Berlaku:**

*   **Pasal 427:** Ancaman hukuman adalah pidana penjara paling lama 3 (tiga) tahun atau pidana denda paling banyak kategori III.
*   **Pasal 78 (2):**  Besaran denda minimal yang ditetapkan adalah Rp50.000,00.

**4. Urutan Ancaman Hukuman:**

1.  **Denda:**  Karena Pasal 427 mengatur denda sebagai salah satu opsi hukuman, maka denda akan menjadi ancaman utama. Besaran denda akan ditentukan berdasarkan kategori yang berlaku (dalam hal ini kategori III).  Pasal 78 (2) menetapkan minimum Rp50.000,00.
2.  **Penjara:**  Sebagai opsi kedua, terpidana dapat dipenjara selama maksimal 3 tahun jika denda dianggap tidak memadai.

**Catatan Penting:**

*   Dokumen yang diberikan tidak secara spesifik membahas perjudian online. Analisis ini didasarkan pada interpretasi Pasal 427 yang paling relevan dengan konteks permainan judi secara umum.
*   Perjudian online saat ini diatur oleh Undang-Undang Pelindungan Anak dari Perjudian dan Undang-Undang ITE.  Pasal-pasal ini mungkin lebih relevan dalam kasus perjudian online modern.

**Disclaimer:** Analisis ini hanya berdasarkan dokumen yang diberikan dan bersifat interpretatif. Untuk mendapatkan jawaban yang lebih akurat dan komprehensif, disarankan untuk berkonsultasi dengan ahli hukum pidana yang memiliki keahlian khusus dalam bidang perjudian dan hukum elektronik.

In [16]:
import json
from tqdm import tqdm

# Load test data
with open("/Users/muhammadzuamaalamin/Documents/RisetTextMining/retrieval2/datates2.json", "r", encoding="utf-8") as f:
    test_data = json.load(f)

# Ekstrak semua field yang relevan dari data test
questions        = [item["question"]        for item in test_data]
references       = [item["answer"]          for item in test_data]
relevant_pasals  = [item["relevant_pasal"]  for item in test_data]
topics           = [item["topic"]           for item in test_data]


def run_qa(chain, question):
    response = chain.invoke({"query": question})
    return response["result"]


# Jalankan evaluasi per item
results = []

for item in tqdm(test_data, desc="Evaluasi QA", unit="soal", colour="green"):
    question       = item["question"]
    reference      = item["answer"]
    relevant_pasal = item["relevant_pasal"]
    topic          = item["topic"]

    # Jalankan chain
    predicted = run_qa(qa_chain, question)

    # Cek apakah pasal yang relevan muncul di jawaban model
    pasal_found  = [p for p in relevant_pasal if p in predicted]
    pasal_missed = [p for p in relevant_pasal if p not in predicted]

    pasal_acc = len(pasal_found) / len(relevant_pasal) if relevant_pasal else 0

    results.append({
        "topic"          : topic,
        "question"       : question,
        "reference"      : reference,
        "predicted"      : predicted,
        "relevant_pasal" : relevant_pasal,
        "pasal_found"    : pasal_found,
        "pasal_missed"   : pasal_missed,
        "pasal_accuracy" : pasal_acc
    })

    # Update tqdm postfix dengan info real-time
    tqdm.write(f"\n{'='*60}")
    tqdm.write(f"Topic   : {topic}")
    tqdm.write(f"Q       : {question}")
    tqdm.write(f"Pasal   : {relevant_pasal}")
    tqdm.write(f"Found   : {pasal_found}")
    tqdm.write(f"Missed  : {pasal_missed}")
    tqdm.write(f"Accuracy: {pasal_acc:.0%}")
    tqdm.write(f"Answer  : {predicted[:200]}...")


# Ringkasan akhir
total         = len(results)
avg_pasal_acc = sum(r["pasal_accuracy"] for r in results) / total

print(f"\n{'='*60}")
print(f"SUMMARY")
print(f"{'='*60}")
print(f"Total Questions  : {total}")
print(f"Avg Pasal Acc    : {avg_pasal_acc:.2%}")


# Simpan hasil ke file
with open("eval_resultsallminilm.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print("\nHasil evaluasi disimpan ke eval_results.json")

Evaluasi QA:   4%|▍         | 1/25 [00:21<08:35, 21.49s/soal]

============================================================
Topic   : Penghinaan dan Pencemaran Nama Baik
Q       : Kalau saya menghina orang di media sosial, ancamannya berapa tahun penjara?
Pasal   : ['433', '441']
Found   : ['433']
Missed  : ['441']
Accuracy: 50%
Answer  : Baik, berdasarkan pertanyaan Anda mengenai ancaman penjara jika menghina orang di media sosial, berikut analisisnya berdasarkan dokumen KUHP yang tersedia:

**1. Pasal-pasal KUHP yang Relevan beserta ...

Evaluasi QA:   8%|▊         | 2/25 [00:39<07:29, 19.56s/soal]

============================================================
Topic   : Perjudian
Q       : Berapa denda maksimal kalau ketahuan main judi online?
Pasal   : ['426', '427']
Found   : ['427']
Missed  : ['426']
Accuracy: 50%
Answer  : Baik, berdasarkan dokumen KUHP yang Anda berikan, berikut adalah analisis mengenai denda maksimal jika ketahuan main judi online:

**1. Pasal-pasal KUHP yang Relevan:**

*   **Pasal 427** “Setiap Oran...

Evaluasi QA:  12%|█▏        | 3/25 [00:59<07:15, 19.80s/soal]

============================================================
Topic   : Pornografi
Q       : Kalau menyebarkan konten porno di WhatsApp, hukumannya seberapa berat?
Pasal   : ['407']
Found   : []
Missed  : ['407']
Accuracy: 0%
Answer  : Baik, berdasarkan konteks dokumen yang diberikan, berikut analisis mengenai hukuman atas penyebaran konten porno di WhatsApp:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 433 ayat (2) huruf b:*...

Evaluasi QA:  16%|█▌        | 4/25 [01:23<07:31, 21.48s/soal]

============================================================
Topic   : Perzinaan
Q       : Apa hukuman untuk orang yang melakukan persetubuhan dengan orang yang bukan suami/istrinya?
Pasal   : ['411']
Found   : ['411']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang Anda berikan, berikut adalah analisis mengenai hukuman untuk orang yang melakukan persetubuhan dengan orang yang bukan suami/istrinya:

**1. Pasal-Pasal KUHP yang R...

Evaluasi QA:  20%|██        | 5/25 [01:45<07:13, 21.65s/soal]

============================================================
Topic   : Perbuatan Cabul
Q       : Kalau memaksa seseorang melakukan perbuatan cabul dengan kekerasan, ancamannya berapa?
Pasal   : ['414', '416']
Found   : ['414']
Missed  : ['416']
Accuracy: 50%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut analisis mengenai ancaman hukuman untuk memaksa seseorang melakukan perbuatan cabul dengan kekerasan:

**1. Pasal-Pasal KUHP yang Relevan:**

*  ...

Evaluasi QA:  24%|██▍       | 6/25 [02:13<07:32, 23.81s/soal]

============================================================
Topic   : Penelantaran Orang
Q       : Berapa hukuman untuk orang tua yang menelantarkan anaknya?
Pasal   : ['428']
Found   : []
Missed  : ['428']
Accuracy: 0%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis mengenai hukuman untuk orang tua yang menelantarkan anaknya:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 429 (1):** “Seti...

Evaluasi QA:  28%|██▊       | 7/25 [02:43<07:43, 25.77s/soal]

============================================================
Topic   : Pemalsuan Surat Keterangan
Q       : Kalau memalsu surat keterangan dokter, ancamannya seberapa berat?
Pasal   : ['395']
Found   : []
Missed  : ['395']
Accuracy: 0%
Answer  : Baik, berdasarkan dokumen KUHP yang Anda berikan, berikut analisis mengenai ancaman hukuman untuk memalsu surat keterangan dokter:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 393 KUHP:** “Dipi...

Evaluasi QA:  32%|███▏      | 8/25 [03:03<06:45, 23.83s/soal]

============================================================
Topic   : Pemalsuan Mata Uang
Q       : Apa hukuman untuk orang yang memalsu uang rupiah?
Pasal   : ['374', '375']
Found   : ['374']
Missed  : ['375']
Accuracy: 50%
Answer  : Baik, berdasarkan dokumen KUHP yang Anda berikan, berikut adalah analisis mengenai hukuman untuk orang yang memalsu uang rupiah:

**1. Pasal-pasal KUHP yang Relevan:**

*   **Pasal 374:** “Setiap Oran...

Evaluasi QA:  36%|███▌      | 9/25 [03:33<06:53, 25.86s/soal]

============================================================
Topic   : Penghinaan Terhadap Agama
Q       : Kalau menghasut orang untuk membenci agama tertentu di media sosial, hukumannya apa?
Pasal   : ['300', '301']
Found   : ['300']
Missed  : ['301']
Accuracy: 50%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis hukum terkait dengan kasus menghasut orang untuk membenci agama tertentu di media sosial:

**1. Pasal-Pasal KUHP yang Relevan:**
...

Evaluasi QA:  40%|████      | 10/25 [03:59<06:27, 25.82s/soal]

============================================================
Topic   : Gangguan Ibadah
Q       : Berapa denda kalau mengganggu ibadah orang lain di tempat ibadah?
Pasal   : ['303']
Found   : ['303']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis mengenai denda jika mengganggu ibadah orang lain di tempat ibadah:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 303 (1):**...

Evaluasi QA:  44%|████▍     | 11/25 [04:28<06:15, 26.82s/soal]

============================================================
Topic   : Penganiayaan Hewan
Q       : Kalau menganiaya hewan peliharaan orang, ancamannya berapa?
Pasal   : ['337']
Found   : ['337']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis mengenai ancaman hukuman untuk menganiaya hewan peliharaan orang:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 337 ayat (1...

Evaluasi QA:  48%|████▊     | 12/25 [04:56<05:55, 27.33s/soal]

============================================================
Topic   : Jual Beli Organ Tubuh
Q       : Apa hukuman untuk orang yang menjual organ tubuh manusia?
Pasal   : ['345']
Found   : ['345']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis mengenai hukuman untuk orang yang menjual organ tubuh manusia:

**1. Pasal-pasal KUHP yang Relevan:**

*   **Pasal 345 ayat (1)**...

Evaluasi QA:  52%|█████▏    | 13/25 [05:17<05:01, 25.13s/soal]

============================================================
Topic   : Tidak Memberi Pertolongan
Q       : Kalau tidak menolong orang yang sedang dalam bahaya maut, apakah bisa dipidana?
Pasal   : ['432']
Found   : ['432']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan pertanyaan dan konteks dokumen yang diberikan, berikut adalah analisis mengenai apakah seseorang dapat dipidana karena tidak menolong orang yang sedang dalam bahaya maut:

**1. Pasal...

Evaluasi QA:  56%|█████▌    | 14/25 [05:38<04:24, 24.06s/soal]

============================================================
Topic   : Fitnah
Q       : Berapa hukuman untuk fitnah yang dilakukan melalui media sosial?
Pasal   : ['434', '441']
Found   : []
Missed  : ['434', '441']
Accuracy: 0%
Answer  : Baik, berdasarkan konteks dokumen KUHP yang diberikan, berikut analisis mengenai hukuman untuk fitnah yang dilakukan melalui media sosial:

**1. Pasal-Pasal KUHP yang Relevan beserta Bunyinya:**

*   ...

Evaluasi QA:  60%|██████    | 15/25 [05:59<03:50, 23.09s/soal]

============================================================
Topic   : Minuman Memabukkan
Q       : Kalau memaksa orang minum minuman keras sampai mabuk, ancamannya apa?
Pasal   : ['424']
Found   : ['424']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis mengenai ancaman hukuman jika seseorang memaksa orang minum minuman keras sampai mabuk:

**1. Pasal-Pasal KUHP yang Relevan:**

*...

Evaluasi QA:  64%|██████▍   | 16/25 [06:16<03:12, 21.40s/soal]

============================================================
Topic   : Eksploitasi Anak
Q       : Apa hukuman untuk orang yang memanfaatkan anak untuk mengemis?
Pasal   : ['425']
Found   : ['425']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut analisis mengenai hukuman untuk orang yang memanfaatkan anak untuk mengemis:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 425 (1):** “Seti...

Evaluasi QA:  68%|██████▊   | 17/25 [06:32<02:36, 19.59s/soal]

============================================================
Topic   : Perusakan Makam
Q       : Kalau merusak makam orang, ancamannya berapa?
Pasal   : ['269']
Found   : ['269']
Missed  : []
Accuracy: 100%
Answer  : Berdasarkan dokumen KUHP yang tersedia, berikut adalah analisis mengenai ancaman hukuman untuk merusak makam orang:

**1. Pasal yang Relevan beserta Bunyinya:**

*   **Pasal 269:** “Setiap Orang yang ...

Evaluasi QA:  72%|███████▏  | 18/25 [06:54<02:22, 20.33s/soal]

============================================================
Topic   : Berita Bohong
Q       : Berapa denda kalau ketahuan menyebar berita bohong yang bikin rusuh?
Pasal   : ['263']
Found   : ['263']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang Anda berikan, berikut analisis mengenai denda jika ketahuan menyebarkan berita bohong yang menyebabkan rusuh:

**1. Pasal-Pasal KUHP yang Relevan:**

*   **Pasal 26...

Evaluasi QA:  76%|███████▌  | 19/25 [07:14<02:01, 20.26s/soal]

============================================================
Topic   : Memaksa Masuk Rumah
Q       : Apa hukuman untuk orang yang memaksa masuk ke rumah orang lain?
Pasal   : ['257']
Found   : ['257']
Missed  : []
Accuracy: 100%
Answer  : Baik, berdasarkan dokumen KUHP yang diberikan, berikut adalah analisis hukum untuk pertanyaan mengenai hukuman atas orang yang memaksa masuk ke rumah orang lain:

**1. Pasal-Pasal KUHP yang Relevan:**...

Evaluasi QA:  76%|███████▌  | 19/25 [07:34<02:23, 23.92s/soal]

KeyboardInterrupt:

In [38]:
questions

['Apa yang dimaksud dengan tanaman tebu?',
 'Apa kepanjangan dari MBS dalam konteks tebu layak giling?',
 'Berapa kisaran curah hujan yang sesuai untuk budidaya tebu?',
 'Apa saja dua pola tanam tebu yang disebutkan dalam pedoman?',
 'Apa fungsi utama kegiatan klentek pada tanaman tebu?',
 'Berapa minimal kebutuhan benih bagal mata 2-3 per hektar?',
 'Apa yang dimaksud dengan Plant Cane (PC)?',
 'Berapa minimal umur tebu agar layak giling?',
 'Alat apa yang digunakan untuk mengukur kedalaman permukaan air tanah?',
 'Penyakit apa yang disebabkan oleh bakteri Leaf sonia xyli subsp.xyli?',
 'Apa yang dimaksud dengan varietas tebu unggul?',
 'Sebutkan dua bentuk benih tebu yang dapat digunakan.',
 'Apa nama sistem pengolahan tanah pada lahan sawah yang dikerjakan secara manual dengan pembuatan saluran air?',
 'Apa fungsi pekerjaan gulud pada budidaya tebu?',
 'Hama apakah yang gejala serangannya ditandai dengan cambuk hitam pada pucuk tanaman?',
 'Berapa batas toleransi kadar kotoran pada tebu giling agar dikategorikan bersih?',
 'Apa yang harus dilakukan terhadap benih bagal sebelum tanam untuk mencegah penyakit?',
 'Sebutkan satu cara pengendalian hama tikus secara biologis.',
 'Apa tujuan utama dari kegiatan turun tanah pertama (Turun Tanah I)?',
 'Pada sistem tebang mekanis, alat apa yang digunakan untuk memuat tebu lonjoran ke truk?']

In [39]:
references

['Tanaman tebu adalah jenis tanaman semusim yang mengandung sukrosa atau yang mengandung kadar gula dan dibudidayakan untuk bahan baku pabrik gula.',
 'Masak, Bersih, dan Segar.',
 'Curah hujan antara 1.000–2.000 milimeter per tahun dengan sekurang-kurangnya 3 bulan kering.',
 'Pola A/I (lahan berpengairan, tanam April-Agustus) dan Pola B/II (lahan tadah hujan, tanam September-November).',
 'Untuk mengelupas daun tebu yang telah kering atau kuning, melancarkan sirkulasi udara dan cahaya, serta mengurangi kelembaban.',
 'Minimal 60.000 mata per hektar.',
 'Tanaman tebu pertama yang berasal dari lahan bukan bekas tebu, menggunakan benih unggul dan bersertifikat.',
 'Minimal 11 (sebelas) bulan.',
 'Pipa Piezometer.',
 'Penyakit Pembuluh Ratoon Stunting Disease (RSD).',
 'Varietas tebu yang menunjukkan adaptasi dan produktivitas yang tinggi, serta memiliki keunggulan-keunggulan tertentu baik dari aspek keragaan tanaman maupun parameter pabrikasi.',
 'Benih berupa setek batang/bagal mata 2 atau 3, dan benih tumbuh berasal dari budset atau budchip yang disemaikan.',
 'Sistem Reynoso.',
 'Mengokohkan berdirinya tanaman dan melancarkan drainase agar tanaman tidak roboh saat hujan deras.',
 'Penyakit Luka Api, yang disebabkan oleh jamur Ustilago scitaminea Sydow.',
 'Kurang dari 5%.',
 'Desinfeksi alat pemotong yang tajam setiap 3-4 kali pemotongan dengan dicelupkan ke dalam larutan desinfektan.',
 'Pemeliharaan Burung Hantu (Tyto alba).',
 'Sebagai media tumbuh tunas dan pengendalian gulma.',
 'Grab Loader.']

In [22]:
import numpy as np
from tqdm import tqdm
from rouge_score import rouge_scorer
from bert_score import score as bert_score


# ── 1. Pastikan predictions & references diambil dari results ──────────────
predictions = [r["predicted"]  for r in results]
references  = [r["reference"]  for r in results]


# ── 2. ROUGE-L ─────────────────────────────────────────────────────────────
def evaluate_rouge_l(predictions, references):
    scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)
    scores = []

    for pred, ref in tqdm(zip(predictions, references),
                          total=len(predictions),
                          desc="ROUGE-L",
                          colour="cyan"):
        score = scorer.score(ref, pred)
        scores.append(score["rougeL"].fmeasure)

    return {
        "rougeL_mean"  : np.mean(scores),
        "rougeL_scores": scores
    }


# ── 3. BERTScore ───────────────────────────────────────────────────────────
def evaluate_bertscore(predictions, references):
    P, R, F1 = bert_score(
        predictions,
        references,
        lang="id",
        model_type="bert-base-multilingual-cased",
        verbose=True
    )

    return {
        "precision": P.mean().item(),
        "recall"   : R.mean().item(),
        "f1"       : F1.mean().item(),
        "f1_scores": F1.tolist()          # per-item score
    }


# ── 4. Jalankan evaluasi ───────────────────────────────────────────────────
print("\n" + "="*60)
print("MENGHITUNG ROUGE-L ...")
print("="*60)
rouge_result = evaluate_rouge_l(predictions, references)

print("\n" + "="*60)
print("MENGHITUNG BERTScore ...")
print("="*60)
bertscore_result = evaluate_bertscore(predictions, references)

============================================================
MENGHITUNG ROUGE-L ...
============================================================

ROUGE-L: 100%|██████████| 25/25 [00:00<00:00, 190.80it/s]

============================================================
MENGHITUNG BERTScore ...
============================================================

calculating scores...
computing bert embedding.

  0%|          | 0/1 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/1 [00:00<?, ?it/s]

done in 4.95 seconds, 5.05 sentences/sec

In [ ]:
# ── 5. Tampilkan ringkasan ─────────────────────────────────────────────────
print("\n" + "="*60)
print("HASIL EVALUASI LENGKAP")
print("="*60)
print(f"Pasal Accuracy (avg) : {avg_pasal_acc:.2%}")
print(f"ROUGE-L (mean)       : {rouge_result['rougeL_mean']:.4f}")
print(f"BERTScore Precision  : {bertscore_result['precision']:.4f}")
print(f"BERTScore Recall     : {bertscore_result['recall']:.4f}")
print(f"BERTScore F1         : {bertscore_result['f1']:.4f}")


# ── 6. Gabungkan semua metric ke results & simpan ─────────────────────────
for i, r in enumerate(results):
    r["rougeL"]          = rouge_result["rougeL_scores"][i]
    r["bertscore_f1"]    = bertscore_result["f1_scores"][i]

with open("eval_results.json", "w", encoding="utf-8") as f:
    import json
    json.dump({
        "summary": {
            "total_questions"   : len(results),
            "avg_pasal_accuracy": avg_pasal_acc,
            "rougeL_mean"       : rouge_result["rougeL_mean"],
            "bertscore_precision": bertscore_result["precision"],
            "bertscore_recall"  : bertscore_result["recall"],
            "bertscore_f1"      : bertscore_result["f1"]
        },
        "details": results
    }, f, ensure_ascii=False, indent=2)

print("\nHasil lengkap disimpan ke eval_results.json")

============================================================
HASIL EVALUASI LENGKAP
============================================================
Pasal Accuracy (avg) : 70.00%
ROUGE-L (mean)       : 0.1648
BERTScore Precision  : 0.6169
BERTScore Recall     : 0.7632
BERTScore F1         : 0.6820

Hasil lengkap disimpan ke eval_results.json